version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nexustock-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: nexustock_main
      POSTGRES_USER: kingsman
      POSTGRES_PASSWORD: 43zTV!^FiU2g!!nXc3RL!6x2&nw@2V9^BM^@!f8&ersTL!9Sj7
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kingsman -d nexustock_main"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexustock-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
