// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexustock.Modules.Wave.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexustock.Modules.Wave.Migrations
{
    [DbContext(typeof(WaveDbContext))]
    partial class WaveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wave")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexustock.Modules.Wave.Entities.PickingWave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("WaveNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WaveNo")
                        .IsUnique();

                    b.ToTable("picking_waves", "wave");
                });

            modelBuilder.Entity("Nexustock.Modules.Wave.Entities.WaveItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtyAllocated")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QtyExpected")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QtyPicked")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QtySorted")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WaveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WaveId");

                    b.ToTable("wave_items", "wave");
                });

            modelBuilder.Entity("Nexustock.Modules.Wave.Entities.WavePickTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtyPicked")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QtyToPick")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WaveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("wave_pick_tasks", "wave");
                });

            modelBuilder.Entity("Nexustock.Modules.Wave.Entities.WaveItem", b =>
                {
                    b.HasOne("Nexustock.Modules.Wave.Entities.PickingWave", null)
                        .WithMany("Items")
                        .HasForeignKey("WaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexustock.Modules.Wave.Entities.PickingWave", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
