// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexustock.Modules.TaskInterleaving.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexustock.Modules.TaskInterleaving.Migrations
{
    [DbContext(typeof(TaskInterleavingDbContext))]
    [Migration("20260720094852_AddTaskInterleavingIdempotency")]
    partial class AddTaskInterleavingIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("task_interleaving")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexustock.Modules.TaskInterleaving.Entities.TaskRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("CurrentLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LaborSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SelectedScore")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SelectedTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedTaskType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceTaskType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AcceptIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_recommendations_tenant_idempotency")
                        .HasFilter("\"AcceptIdempotencyKey\" IS NOT NULL");

                    b.HasIndex("TenantId", "ExpiresAt")
                        .HasDatabaseName("idx_recommendations_tenant_expires");

                    b.HasIndex("TenantId", "SelectedTaskType", "SelectedTaskId")
                        .HasDatabaseName("idx_recommendations_tenant_selected_task");

                    b.HasIndex("TenantId", "UserId", "Status", "CreatedAt")
                        .HasDatabaseName("idx_recommendations_tenant_user_status_created");

                    b.ToTable("task_recommendations", "task_interleaving");
                });

            modelBuilder.Entity("Nexustock.Modules.TaskInterleaving.Entities.TaskRecommendationCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AgeScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("AgeSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("ContinuityScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DistanceScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("PenaltyScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriorityScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId", "TotalScore")
                        .HasDatabaseName("idx_candidates_recommendation_score");

                    b.ToTable("task_recommendation_candidates", "task_interleaving");
                });
#pragma warning restore 612, 618
        }
    }
}
