// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexustock.Modules.Inbound.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexustock.Modules.Inbound.Migrations
{
    [DbContext(typeof(InboundDbContext))]
    partial class InboundDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexustock.Modules.Inbound.Entities.InboundOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("uq_inbound_orders_tenant_orderno");

                    b.ToTable("InboundOrders");
                });

            modelBuilder.Entity("Nexustock.Modules.Inbound.Entities.InboundOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExpectedQty")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InboundOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReceivedQty")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Tolerance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InboundOrderId");

                    b.ToTable("InboundOrderItems");
                });

            modelBuilder.Entity("Nexustock.Modules.Inbound.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LotNo", "ItemId")
                        .HasDatabaseName("idx_inv_trans_tenant_lot_item");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("Nexustock.Modules.Inbound.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QcStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LotNo", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_lots_tenant_lotno_itemid");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("Nexustock.Modules.Inbound.Entities.InboundOrderItem", b =>
                {
                    b.HasOne("Nexustock.Modules.Inbound.Entities.InboundOrder", "InboundOrder")
                        .WithMany("Items")
                        .HasForeignKey("InboundOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboundOrder");
                });

            modelBuilder.Entity("Nexustock.Modules.Inbound.Entities.InboundOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
