// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexustock.Modules.MasterData.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexustock.Modules.MasterData.Migrations
{
    [DbContext(typeof(MasterDataDbContext))]
    [Migration("20260702023333_InitialMasterData")]
    partial class InitialMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("integer")
                        .HasColumnName("error_rows");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("import_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("SuccessRows")
                        .HasColumnType("integer")
                        .HasColumnName("success_rows");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("import_batches");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.ImportBatchRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("import_batch_rows");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("numeric")
                        .HasColumnName("conversion_factor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("package_name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uuid")
                        .HasColumnName("uom_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("UomId");

                    b.HasIndex("ProductId", "UomId")
                        .IsUnique()
                        .HasDatabaseName("uq_packages_product_uom");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("uq_packages_tenant_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.ToTable("packages");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("partner_type");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_partners_tenant_code");

                    b.ToTable("partners");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<Guid>("BaseUomId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_uom_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("BaseUomId");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("uq_products_tenant_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_products_tenant_code");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.ProductConfig", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<string>("IqcCheckType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("iqc_check_type");

                    b.Property<bool>("IsWafer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_wafer");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("LotValidationRegex")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lot_validation_regex");

                    b.Property<decimal>("MaxStock")
                        .HasColumnType("numeric")
                        .HasColumnName("max_stock");

                    b.Property<decimal>("MinStock")
                        .HasColumnType("numeric")
                        .HasColumnName("min_stock");

                    b.Property<string>("RotationSpeed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rotation_speed");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TrackSerial")
                        .HasColumnType("boolean")
                        .HasColumnName("track_serial");

                    b.Property<bool>("VendorInnerLotCtl")
                        .HasColumnType("boolean")
                        .HasColumnName("vendor_inner_lot_ctl");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.Property<string>("WeightClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("weight_class");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.HasKey("ProductId");

                    b.HasIndex("TenantId");

                    b.ToTable("product_configs");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.ReasonCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ReasonType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reason_type");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReasonType", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_reason_codes_tenant_type_code");

                    b.ToTable("reason_codes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            Code = "HOLD-QC",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4482), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            Description = "Chờ QC kiểm tra chất lượng",
                            IsActive = true,
                            ReasonType = "HOLD",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            Code = "ADJ-COUNT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4485), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            Description = "Điều chỉnh số lượng kiểm kê",
                            IsActive = true,
                            ReasonType = "INVENTORY_ADJUSTMENT",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("LockReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lock_reason_code");

                    b.Property<decimal>("MaxCapacity")
                        .HasColumnType("numeric")
                        .HasColumnName("max_capacity");

                    b.Property<decimal>("MaxVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("max_volume");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.Property<int>("XCoord")
                        .HasColumnType("integer")
                        .HasColumnName("x_coord");

                    b.Property<int>("YCoord")
                        .HasColumnType("integer")
                        .HasColumnName("y_coord");

                    b.Property<int>("ZCoord")
                        .HasColumnType("integer")
                        .HasColumnName("z_coord");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("idx_storage_locations_code");

                    b.ToTable("storage_locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            Code = "LOC-A-01",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4426), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            Height = 0.00m,
                            IsActive = true,
                            IsLocked = false,
                            Length = 0.00m,
                            MaxCapacity = 1000m,
                            MaxVolume = 1000m,
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Width = 0.00m,
                            XCoord = 1,
                            YCoord = 1,
                            ZCoord = 1,
                            ZoneId = new Guid("00000000-0000-0000-0000-000000000031")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            Code = "LOC-A-02",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4435), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            Height = 0.00m,
                            IsActive = true,
                            IsLocked = false,
                            Length = 0.00m,
                            MaxCapacity = 1000m,
                            MaxVolume = 1000m,
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Width = 0.00m,
                            XCoord = 1,
                            YCoord = 2,
                            ZCoord = 1,
                            ZoneId = new Guid("00000000-0000-0000-0000-000000000031")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            Code = "LOC-QC-01",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4463), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            Height = 0.00m,
                            IsActive = true,
                            IsLocked = false,
                            Length = 0.00m,
                            MaxCapacity = 500m,
                            MaxVolume = 500m,
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Width = 0.00m,
                            XCoord = 2,
                            YCoord = 1,
                            ZCoord = 1,
                            ZoneId = new Guid("00000000-0000-0000-0000-000000000032")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            Code = "LOC-QC-02",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4466), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            Height = 0.00m,
                            IsActive = true,
                            IsLocked = false,
                            Length = 0.00m,
                            MaxCapacity = 500m,
                            MaxVolume = 500m,
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Width = 0.00m,
                            XCoord = 2,
                            YCoord = 2,
                            ZCoord = 1,
                            ZoneId = new Guid("00000000-0000-0000-0000-000000000032")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            Code = "LOC-STG-01",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4468), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            Height = 0.00m,
                            IsActive = true,
                            IsLocked = false,
                            Length = 0.00m,
                            MaxCapacity = 2000m,
                            MaxVolume = 2000m,
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Width = 0.00m,
                            XCoord = 3,
                            YCoord = 1,
                            ZCoord = 1,
                            ZoneId = new Guid("00000000-0000-0000-0000-000000000033")
                        });
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.StorageZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<decimal?>("TemperatureLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature_limit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zone_type");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("TenantId", "WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_storage_zones_tenant_warehouse_code");

                    b.ToTable("storage_zones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Code = "ZONE-STORAGE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4409), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            IsLocked = false,
                            Name = "Khu lưu trữ chính",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            WarehouseId = new Guid("00000000-0000-0000-0000-000000000021"),
                            ZoneType = "STORAGE"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Code = "ZONE-QC",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4412), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            IsLocked = false,
                            Name = "Khu kiểm tra chất lượng",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            WarehouseId = new Guid("00000000-0000-0000-0000-000000000021"),
                            ZoneType = "QC"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            Code = "ZONE-STAGING",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4414), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            IsLocked = false,
                            Name = "Khu trung chuyển",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            WarehouseId = new Guid("00000000-0000-0000-0000-000000000021"),
                            ZoneType = "STAGING"
                        });
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_tenants_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_tenants_active");

                    b.ToTable("tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "DEFAULT-TENANT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Name = "Default Tenant",
                            RowVersion = 1
                        });
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.TenantConfig", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("AllowNegativeStock")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_negative_stock");

                    b.Property<int>("FifoPolicyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("fifo_policy_level");

                    b.Property<string>("LotNoPattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_no_pattern");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_configs");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            AllowNegativeStock = false,
                            FifoPolicyLevel = 2,
                            LotNoPattern = "{YYYY}{MM}{DD}-{SEQ}"
                        });
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Uom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_uoms_tenant_code");

                    b.ToTable("uoms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Code = "PCS",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4380), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Name = "Cái",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Code = "BOX",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4382), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Name = "Hộp",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Code = "PALLET",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4384), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Name = "Pallet",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_warehouses_tenant_code");

                    b.ToTable("warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Code = "WH-MAIN",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 2, 33, 33, 742, DateTimeKind.Unspecified).AddTicks(4396), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Name = "Kho chính",
                            RowVersion = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.ImportBatch", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.ImportBatchRow", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.ImportBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Package", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexustock.Modules.MasterData.Entities.Uom", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tenant");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Partner", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Product", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Uom", "BaseUom")
                        .WithMany()
                        .HasForeignKey("BaseUomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseUom");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.ProductConfig", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.ReasonCode", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.StorageLocation", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexustock.Modules.MasterData.Entities.StorageZone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.StorageZone", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexustock.Modules.MasterData.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.TenantConfig", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Uom", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexustock.Modules.MasterData.Entities.Warehouse", b =>
                {
                    b.HasOne("Nexustock.Modules.MasterData.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
